version: "3.9"
services:
  web:
    build: .
    depends_on:
      - "mongodb"
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - "mongodb"